///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace browser
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the browserRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("39bc0771-0242-4ce1-86db-5a5809a84881")]
    public partial class browserRepository : RepoGenBaseFolder
    {
        static browserRepository instance = new browserRepository();
        browserRepositoryFolders.RanorexSeleniumGridGoogleSearchAppFolder _ranorexseleniumgridgooglesearch;
        browserRepositoryFolders.DashboardAppFolder _dashboard;
        browserRepositoryFolders.ComMygamesolutionsUsAppFolder _commygamesolutionsus;
        browserRepositoryFolders.GoogleAppFolder _google;
        browserRepositoryFolders.Mdi1MdiAppFolder _mdi1mdi;
        browserRepositoryFolders.BrowserAppFolder _browser;

        /// <summary>
        /// Gets the singleton class instance representing the browserRepository element repository.
        /// </summary>
        [RepositoryFolder("39bc0771-0242-4ce1-86db-5a5809a84881")]
        public static browserRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public browserRepository() 
            : base("browserRepository", "/", null, 0, false, "39bc0771-0242-4ce1-86db-5a5809a84881", ".\\RepositoryImages\\browserRepository39bc0771.rximgres")
        {
            _ranorexseleniumgridgooglesearch = new browserRepositoryFolders.RanorexSeleniumGridGoogleSearchAppFolder(this);
            _dashboard = new browserRepositoryFolders.DashboardAppFolder(this);
            _commygamesolutionsus = new browserRepositoryFolders.ComMygamesolutionsUsAppFolder(this);
            _google = new browserRepositoryFolders.GoogleAppFolder(this);
            _mdi1mdi = new browserRepositoryFolders.Mdi1MdiAppFolder(this);
            _browser = new browserRepositoryFolders.BrowserAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("39bc0771-0242-4ce1-86db-5a5809a84881")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexSeleniumGridGoogleSearch folder.
        /// </summary>
        [RepositoryFolder("80d49d37-1555-47f3-9aca-67e91d5d8069")]
        public virtual browserRepositoryFolders.RanorexSeleniumGridGoogleSearchAppFolder RanorexSeleniumGridGoogleSearch
        {
            get { return _ranorexseleniumgridgooglesearch; }
        }

        /// <summary>
        /// The Dashboard folder.
        /// </summary>
        [RepositoryFolder("ada89489-3364-4ccf-bde5-08eba1b8c649")]
        public virtual browserRepositoryFolders.DashboardAppFolder Dashboard
        {
            get { return _dashboard; }
        }

        /// <summary>
        /// The ComMygamesolutionsUs folder.
        /// </summary>
        [RepositoryFolder("daf2e90f-32fb-4e73-adda-bc0699f45813")]
        public virtual browserRepositoryFolders.ComMygamesolutionsUsAppFolder ComMygamesolutionsUs
        {
            get { return _commygamesolutionsus; }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("7968915b-dfd9-4eca-9810-9227b16036df")]
        public virtual browserRepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }

        /// <summary>
        /// The Mdi1Mdi folder.
        /// </summary>
        [RepositoryFolder("f81abb72-6e38-4c7f-9902-d0d95a3e7de8")]
        public virtual browserRepositoryFolders.Mdi1MdiAppFolder Mdi1Mdi
        {
            get { return _mdi1mdi; }
        }

        /// <summary>
        /// The Browser folder.
        /// </summary>
        [RepositoryFolder("9e9fa911-f121-4e34-8e3c-e9b97fed3210")]
        public virtual browserRepositoryFolders.BrowserAppFolder Browser
        {
            get { return _browser; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class browserRepositoryFolders
    {
        /// <summary>
        /// The RanorexSeleniumGridGoogleSearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("80d49d37-1555-47f3-9aca-67e91d5d8069")]
        public partial class RanorexSeleniumGridGoogleSearchAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _getedgetoshowupinseleniumgridgInfo;

            /// <summary>
            /// Creates a new RanorexSeleniumGridGoogleSearch  folder.
            /// </summary>
            public RanorexSeleniumGridGoogleSearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexSeleniumGridGoogleSearch", "/dom[@caption~'^Ranorex\\ Selenium\\ Grid\\ -\\ G']", parentFolder, 30000, null, false, "80d49d37-1555-47f3-9aca-67e91d5d8069", "")
            {
                _getedgetoshowupinseleniumgridgInfo = new RepoItemInfo(this, "GetEdgeToShowUpInSeleniumGridG", ".//div[#'rso']/div/div[@innertext='']/div[1]//h3[@innertext='']/a[@innertext~'^Get\\ edge\\ to\\ show\\ up\\ in\\ Se']", 30000, null, "22e8209b-bcec-4a4e-b2c0-e4405efc72f6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80d49d37-1555-47f3-9aca-67e91d5d8069")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80d49d37-1555-47f3-9aca-67e91d5d8069")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GetEdgeToShowUpInSeleniumGridG item.
            /// </summary>
            [RepositoryItem("22e8209b-bcec-4a4e-b2c0-e4405efc72f6")]
            public virtual Ranorex.ATag GetEdgeToShowUpInSeleniumGridG
            {
                get
                {
                    return _getedgetoshowupinseleniumgridgInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GetEdgeToShowUpInSeleniumGridG item info.
            /// </summary>
            [RepositoryItemInfo("22e8209b-bcec-4a4e-b2c0-e4405efc72f6")]
            public virtual RepoItemInfo GetEdgeToShowUpInSeleniumGridGInfo
            {
                get
                {
                    return _getedgetoshowupinseleniumgridgInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardAppFolder folder.
        /// </summary>
        [RepositoryFolder("ada89489-3364-4ccf-bde5-08eba1b8c649")]
        public partial class DashboardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dockstoptestingInfo;

            /// <summary>
            /// Creates a new Dashboard  folder.
            /// </summary>
            public DashboardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dashboard", "/dom[@domain='www.browserstack.com']", parentFolder, 30000, null, false, "ada89489-3364-4ccf-bde5-08eba1b8c649", "")
            {
                _dockstoptestingInfo = new RepoItemInfo(this, "DockStopTesting", ".//a[#'dockStopTesting']", 30000, null, "9797e2fb-fc49-454a-b763-9e89aae1072d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ada89489-3364-4ccf-bde5-08eba1b8c649")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ada89489-3364-4ccf-bde5-08eba1b8c649")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DockStopTesting item.
            /// </summary>
            [RepositoryItem("9797e2fb-fc49-454a-b763-9e89aae1072d")]
            public virtual Ranorex.ATag DockStopTesting
            {
                get
                {
                    return _dockstoptestingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DockStopTesting item info.
            /// </summary>
            [RepositoryItemInfo("9797e2fb-fc49-454a-b763-9e89aae1072d")]
            public virtual RepoItemInfo DockStopTestingInfo
            {
                get
                {
                    return _dockstoptestingInfo;
                }
            }
        }

        /// <summary>
        /// The ComMygamesolutionsUsAppFolder folder.
        /// </summary>
        [RepositoryFolder("daf2e90f-32fb-4e73-adda-bc0699f45813")]
        public partial class ComMygamesolutionsUsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startexploringInfo;
            RepoItemInfo _mainactivityInfo;
            RepoItemInfo _inputusernamevalInfo;
            RepoItemInfo _inputpasswordvalInfo;
            RepoItemInfo _inputpasswordval1Info;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new ComMygamesolutionsUs  folder.
            /// </summary>
            public ComMygamesolutionsUsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComMygamesolutionsUs", "/mobileapp[@title='com.mygamesolutions.us']", parentFolder, 30000, null, false, "daf2e90f-32fb-4e73-adda-bc0699f45813", "")
            {
                _startexploringInfo = new RepoItemInfo(this, "StartExploring", "form[@title='MainActivity']/?/?/dom[@domain='mgsi-tst.outsystemsenterprise.com']//div[#'b1-Content']//div[@innertext='Start Exploring...']", 30000, null, "8ee6b1b4-c19b-4da5-8cd1-8d083b44de13");
                _mainactivityInfo = new RepoItemInfo(this, "MainActivity", "form[@title='MainActivity']", 30000, null, "4993cf87-9ef0-4199-8b3a-6b53b5f7dc44");
                _inputusernamevalInfo = new RepoItemInfo(this, "InputUsernameVal", ".//dom[@domain='mgsi-tst.outsystemsenterprise.com']//input[@id='Input_UsernameVal' and @class='form-control OSFillParent' and @tagname='input']", 30000, null, "9e95d0cf-0d51-4744-ae1d-170557a65a79");
                _inputpasswordvalInfo = new RepoItemInfo(this, "InputPasswordVal", ".//dom[@domain='mgsi-tst.outsystemsenterprise.com']//input[@type='password' and @class='form-control login-password OSFillParent ' and @tagname='input']", 30000, null, "e1a2af02-6566-4a9b-b6c8-feec504582f7");
                _inputpasswordval1Info = new RepoItemInfo(this, "InputPasswordVal1", ".//dom[@domain='mgsi-tst.outsystemsenterprise.com']//input[@type='password' and @id='Input_PasswordVal' and @class='form-control login-password OSFillParent' and @tagname='input']", 30000, null, "4e9aec96-2c39-499c-a6bd-4e50786c1087");
                _loginInfo = new RepoItemInfo(this, "LogIn", "form[@title='MainActivity']/?/?/dom[@domain='mgsi-tst.outsystemsenterprise.com']//div[#'b1-Content']//span[@innertext='Log in']", 30000, null, "d7bcc1cb-ef57-4723-ab50-f569e2bf1ce4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("daf2e90f-32fb-4e73-adda-bc0699f45813")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("daf2e90f-32fb-4e73-adda-bc0699f45813")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The StartExploring item.
            /// </summary>
            [RepositoryItem("8ee6b1b4-c19b-4da5-8cd1-8d083b44de13")]
            public virtual Ranorex.DivTag StartExploring
            {
                get
                {
                    return _startexploringInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The StartExploring item info.
            /// </summary>
            [RepositoryItemInfo("8ee6b1b4-c19b-4da5-8cd1-8d083b44de13")]
            public virtual RepoItemInfo StartExploringInfo
            {
                get
                {
                    return _startexploringInfo;
                }
            }

            /// <summary>
            /// The MainActivity item.
            /// </summary>
            [RepositoryItem("4993cf87-9ef0-4199-8b3a-6b53b5f7dc44")]
            public virtual Ranorex.Form MainActivity
            {
                get
                {
                    return _mainactivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The MainActivity item info.
            /// </summary>
            [RepositoryItemInfo("4993cf87-9ef0-4199-8b3a-6b53b5f7dc44")]
            public virtual RepoItemInfo MainActivityInfo
            {
                get
                {
                    return _mainactivityInfo;
                }
            }

            /// <summary>
            /// The InputUsernameVal item.
            /// </summary>
            [RepositoryItem("9e95d0cf-0d51-4744-ae1d-170557a65a79")]
            public virtual Ranorex.InputTag InputUsernameVal
            {
                get
                {
                    return _inputusernamevalInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputUsernameVal item info.
            /// </summary>
            [RepositoryItemInfo("9e95d0cf-0d51-4744-ae1d-170557a65a79")]
            public virtual RepoItemInfo InputUsernameValInfo
            {
                get
                {
                    return _inputusernamevalInfo;
                }
            }

            /// <summary>
            /// The InputPasswordVal item.
            /// </summary>
            [RepositoryItem("e1a2af02-6566-4a9b-b6c8-feec504582f7")]
            public virtual Ranorex.InputTag InputPasswordVal
            {
                get
                {
                    return _inputpasswordvalInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPasswordVal item info.
            /// </summary>
            [RepositoryItemInfo("e1a2af02-6566-4a9b-b6c8-feec504582f7")]
            public virtual RepoItemInfo InputPasswordValInfo
            {
                get
                {
                    return _inputpasswordvalInfo;
                }
            }

            /// <summary>
            /// The InputPasswordVal1 item.
            /// </summary>
            [RepositoryItem("4e9aec96-2c39-499c-a6bd-4e50786c1087")]
            public virtual Ranorex.InputTag InputPasswordVal1
            {
                get
                {
                    return _inputpasswordval1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPasswordVal1 item info.
            /// </summary>
            [RepositoryItemInfo("4e9aec96-2c39-499c-a6bd-4e50786c1087")]
            public virtual RepoItemInfo InputPasswordVal1Info
            {
                get
                {
                    return _inputpasswordval1Info;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("d7bcc1cb-ef57-4723-ab50-f569e2bf1ce4")]
            public virtual Ranorex.SpanTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("d7bcc1cb-ef57-4723-ab50-f569e2bf1ce4")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("7968915b-dfd9-4eca-9810-9227b16036df")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstibInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@caption='Google']", parentFolder, 30000, null, false, "7968915b-dfd9-4eca-9810-9227b16036df", "")
            {
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "7f683ed0-c224-43e9-92a1-e4510c436cd9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7968915b-dfd9-4eca-9810-9227b16036df")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7968915b-dfd9-4eca-9810-9227b16036df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("7f683ed0-c224-43e9-92a1-e4510c436cd9")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("7f683ed0-c224-43e9-92a1-e4510c436cd9")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }
        }

        /// <summary>
        /// The Mdi1MdiAppFolder folder.
        /// </summary>
        [RepositoryFolder("f81abb72-6e38-4c7f-9902-d0d95a3e7de8")]
        public partial class Mdi1MdiAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _windowInfo;

            /// <summary>
            /// Creates a new Mdi1Mdi  folder.
            /// </summary>
            public Mdi1MdiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Mdi1Mdi", "/form[@processname='Mdi' and @class='Afx:00350000:8:00010003:00000000:006A08C3']", parentFolder, 30000, null, true, "f81abb72-6e38-4c7f-9902-d0d95a3e7de8", "")
            {
                _windowInfo = new RepoItemInfo(this, "Window", ".//container[@accessiblename='Menu Bar']/menuitem[@accessiblename='Window']", 30000, null, "c2937806-38f5-47eb-ac73-e058af35ea00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f81abb72-6e38-4c7f-9902-d0d95a3e7de8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f81abb72-6e38-4c7f-9902-d0d95a3e7de8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Window item.
            /// </summary>
            [RepositoryItem("c2937806-38f5-47eb-ac73-e058af35ea00")]
            public virtual Ranorex.MenuItem Window
            {
                get
                {
                    return _windowInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Window item info.
            /// </summary>
            [RepositoryItemInfo("c2937806-38f5-47eb-ac73-e058af35ea00")]
            public virtual RepoItemInfo WindowInfo
            {
                get
                {
                    return _windowInfo;
                }
            }
        }

        /// <summary>
        /// The BrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("9e9fa911-f121-4e34-8e3c-e9b97fed3210")]
        public partial class BrowserAppFolder : RepoGenBaseFolder
        {
            browserRepositoryFolders.DomAppFolder _dom;
            RepoItemInfo _rxbrowseractivityInfo;
            RepoItemInfo _btnbackInfo;

            /// <summary>
            /// Creates a new Browser  folder.
            /// </summary>
            public BrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Browser", "/mobileapp[@title='ranorex.RxBrowser']", parentFolder, 30000, null, false, "9e9fa911-f121-4e34-8e3c-e9b97fed3210", "")
            {
                _dom = new browserRepositoryFolders.DomAppFolder(this);
                _rxbrowseractivityInfo = new RepoItemInfo(this, "RxBrowserActivity", "form[@title='RxBrowserActivity']", 30000, null, "13516be9-36b8-4c3d-842a-546a0f5ae415");
                _btnbackInfo = new RepoItemInfo(this, "BtnBack", "form[@title='RxBrowserActivity']//container[@rid='Navigation']/button[@accessibilityid='Back']", 30000, null, "e7cdee1d-3a62-45be-ba97-3ced3a09f114");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e9fa911-f121-4e34-8e3c-e9b97fed3210")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e9fa911-f121-4e34-8e3c-e9b97fed3210")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxBrowserActivity item.
            /// </summary>
            [RepositoryItem("13516be9-36b8-4c3d-842a-546a0f5ae415")]
            public virtual Ranorex.Form RxBrowserActivity
            {
                get
                {
                    return _rxbrowseractivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The RxBrowserActivity item info.
            /// </summary>
            [RepositoryItemInfo("13516be9-36b8-4c3d-842a-546a0f5ae415")]
            public virtual RepoItemInfo RxBrowserActivityInfo
            {
                get
                {
                    return _rxbrowseractivityInfo;
                }
            }

            /// <summary>
            /// The BtnBack item.
            /// </summary>
            [RepositoryItem("e7cdee1d-3a62-45be-ba97-3ced3a09f114")]
            public virtual Ranorex.Button BtnBack
            {
                get
                {
                    return _btnbackInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnBack item info.
            /// </summary>
            [RepositoryItemInfo("e7cdee1d-3a62-45be-ba97-3ced3a09f114")]
            public virtual RepoItemInfo BtnBackInfo
            {
                get
                {
                    return _btnbackInfo;
                }
            }

            /// <summary>
            /// The Dom folder.
            /// </summary>
            [RepositoryFolder("6c75ca40-87c8-4cc2-99e0-811b0ad2a211")]
            public virtual browserRepositoryFolders.DomAppFolder Dom
            {
                get { return _dom; }
            }
        }

        /// <summary>
        /// The DomAppFolder folder.
        /// </summary>
        [RepositoryFolder("6c75ca40-87c8-4cc2-99e0-811b0ad2a211")]
        public partial class DomAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lstibInfo;
            RepoItemInfo _enterprisesdefineenterprisesatdictInfo;
            RepoItemInfo _sbicoInfo;

            /// <summary>
            /// Creates a new Dom  folder.
            /// </summary>
            public DomAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dom", ".//dom", parentFolder, 30000, null, false, "6c75ca40-87c8-4cc2-99e0-811b0ad2a211", "")
            {
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "06e2235e-b763-4944-ba8f-f1f2f95b7aba");
                _enterprisesdefineenterprisesatdictInfo = new RepoItemInfo(this, "EnterprisesDefineEnterprisesAtDict", ".//div[#'rso']/div[1]/div[@innertext='']/div[@innertext='']/div[@innertext='']/div[1]/?/?/a[@innertext='']/div[@innertext~'^Enterprises\\ \\|\\ Define\\ Ente']", 30000, null, "44ad4d54-11e1-4505-b952-be88da1818ea");
                _sbicoInfo = new RepoItemInfo(this, "Sbico", ".//button[#'tsbb']/div[@innertext='']", 30000, null, "eea0176a-d2b0-449c-ab03-5477a9e49048");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6c75ca40-87c8-4cc2-99e0-811b0ad2a211")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6c75ca40-87c8-4cc2-99e0-811b0ad2a211")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("06e2235e-b763-4944-ba8f-f1f2f95b7aba")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("06e2235e-b763-4944-ba8f-f1f2f95b7aba")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }

            /// <summary>
            /// The EnterprisesDefineEnterprisesAtDict item.
            /// </summary>
            [RepositoryItem("44ad4d54-11e1-4505-b952-be88da1818ea")]
            public virtual Ranorex.DivTag EnterprisesDefineEnterprisesAtDict
            {
                get
                {
                    return _enterprisesdefineenterprisesatdictInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EnterprisesDefineEnterprisesAtDict item info.
            /// </summary>
            [RepositoryItemInfo("44ad4d54-11e1-4505-b952-be88da1818ea")]
            public virtual RepoItemInfo EnterprisesDefineEnterprisesAtDictInfo
            {
                get
                {
                    return _enterprisesdefineenterprisesatdictInfo;
                }
            }

            /// <summary>
            /// The Sbico item.
            /// </summary>
            [RepositoryItem("eea0176a-d2b0-449c-ab03-5477a9e49048")]
            public virtual Ranorex.DivTag Sbico
            {
                get
                {
                    return _sbicoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sbico item info.
            /// </summary>
            [RepositoryItemInfo("eea0176a-d2b0-449c-ab03-5477a9e49048")]
            public virtual RepoItemInfo SbicoInfo
            {
                get
                {
                    return _sbicoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}