///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace browser
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("15ef3081-9993-44af-8590-2776cd1ca8d1", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the browserRepository repository.
        /// </summary>
        public static browserRepository repo = browserRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'ranorex.RxBrowser' on device 'USB-47f9c2e3'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-47f9c2e3", "ranorex.RxBrowser", false);
            Delay.Milliseconds(3500);
            
            // Browse to site.
            Report.Log(ReportLevel.Info, "Set Value", "Browse to site.\r\nSetting attribute PageUrl to 'www.google.com' on item 'Browser.Dom'.", repo.Browser.Dom.SelfInfo, new RecordItemIndex(1));
            repo.Browser.Dom.Self.Element.SetAttributeValue("PageUrl", "www.google.com");
            Delay.Milliseconds(5000);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Value to 'fhj' on item 'Browser.Dom.LstIb'.", repo.Browser.Dom.LstIbInfo, new RecordItemIndex(2));
            repo.Browser.Dom.LstIb.Element.SetAttributeValue("Value", "fhj");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Browser.Dom.Sbico' at Center", repo.Browser.Dom.SbicoInfo, new RecordItemIndex(3));
            repo.Browser.Dom.Sbico.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Browser.BtnBack' at Center", repo.Browser.BtnBackInfo, new RecordItemIndex(4));
            repo.Browser.BtnBack.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'Browser.RxBrowserActivity'.", repo.Browser.RxBrowserActivityInfo, new RecordItemIndex(5));
            repo.Browser.RxBrowserActivity.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'Browser.RxBrowserActivity'.", repo.Browser.RxBrowserActivityInfo, new RecordItemIndex(6));
            repo.Browser.RxBrowserActivity.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
